[package]
name = "liftlog_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0"
config = "0.13.1"
serde = { version = "1.0.188", features = ["derive", "serde_derive"] }
dotenvy = "0.15.7"
