# Development Docker compose for development postgres database
version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - ./development_data/postgres:/var/lib/postgresql/data
        user: "1000:1000"
