CREATE TABLE IF NOT EXISTS access_tokens (
    token VARCHAR(100) PRIMARY KEY,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT token_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);