name: Run clippy

on:
    push:
    pull_request:

jobs:
    rustfmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install clippy
              working-directory: ./server
              run: |
                  rustup component add clippy
            - name: Run clippy
              working-directory: ./server
              run: |
                  cargo clippy
