name: Test and build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LIFTLOG_DATABASE_URL: "postgresql://postgres:postgres@postgres/liftlog"
  LIFTLOG_LISTEN_ADDRESS: "127.0.0.1:3000"
  DATABASE_URL: "postgresql://postgres:postgres@postgres/liftlog"

jobs:
  build:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./server
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./server
      run: cargo test --verbose
